language: python
python:
  - "3.6.7"
install:
  - pip install .
script:
  - py.test --pep8 easypj/
  - py.test --pep8 tests
  - source tests/custom_encoder/easypj_sample_config.sh && py.test --pep8 tests/custom_encoder
